language: node

before_script: |
  sudo add-apt-repository ppa:jonathonf/vim -y
  sudo apt update
  sudo apt install vim
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/soywod/kronos.vim.git

script: |
  TZ=UTC vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=kronos.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null

